spring:
  application:
    name: smart-lead-ai

  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/leads_db
      username: local_user
      password: local_password
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: hikari-primary
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 3000
        max-lifetime: 1800000
        keepalive-time: 300000

    replica:
      url: jdbc:postgresql://localhost:5433/leads_db?readOnly=true
      username: local_user
      password: local_password
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: hikari-replica
        maximum-pool-size: 20
        minimum-idle: 2
        connection-timeout: 2000
        max-lifetime: 1800000
        keepalive-time: 300000


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10

  threads:
    virtual:
      enabled: true
  flyway:
    enabled: false

huggingface:
  enabled: true
  baseUrl: https://router.huggingface.co
  token: ${{ secrets.HF_TOKEN }}
  maxTokens: 512
  temperature: 0.7
  stream: false
  model: meta-llama/Llama-3.3-70B-Instruct

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


resilience4j:
  retry:
    instances:
      hugginfface:
        max-attempts: 3
        wait-duration:
          seconds: 2
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.SocketTimeoutException
  ratelimiter:
    instances:
      huggingface:
        limit-for-period: 10
        limit-refresh-period:
          seconds: 1
        timeout-duration:
          seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=DEBUG: