services:
  postgres-primary:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: leads_db
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=5
      -c max_replication_slots=5
      -c hot_standby=on
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local_user -d leads_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres-replica:
    image: postgres:17
    ports:
      - "5433:5432"
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      PGPASSWORD: replication_password
    volumes:
      - replica_data:/var/lib/postgresql/data
    command: >
      bash -c "
      if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
        echo 'Cloning primary...';
        pg_basebackup -h postgres-primary -p 5432 -U repl_user -D /var/lib/postgresql/data -Fp -Xs -R;
        chmod 700 /var/lib/postgresql/data;
      fi;
      exec docker-entrypoint.sh postgres
      "
volumes:
  primary_data:
  replica_data: